# Generated by Django 5.2.11 on 2026-02-16 12:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='შექმნის დრო'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='fixed_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fixed End (თუ fixed)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='fixed_start',
            field=models.DateField(blank=True, null=True, verbose_name='Fixed Start (თუ fixed)'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='gymapp.client', verbose_name='კლიენტი'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='შესვლის დრო'),
        ),
        migrations.AlterField(
            model_name='client',
            name='active_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_clients', to='gymapp.membership', verbose_name='აქტიური აბონემენტი'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='სახელი'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='გვარი'),
        ),
        migrations.AlterField(
            model_name='client',
            name='membership_end',
            field=models.DateField(blank=True, null=True, verbose_name='დასრულების თარიღი'),
        ),
        migrations.AlterField(
            model_name='client',
            name='membership_start',
            field=models.DateField(blank=True, null=True, verbose_name='დაწყების თარიღი'),
        ),
        migrations.AlterField(
            model_name='client',
            name='personal_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='პირადი ნომერი'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='ტელეფონი'),
        ),
        migrations.AlterField(
            model_name='client',
            name='remaining_visits',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='დარჩენილი ვიზიტები'),
        ),
        migrations.AlterField(
            model_name='client',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='gymapp.trainer', verbose_name='ტრენერი'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ვადა (დღეებში)'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('unlimited', 'ულიმიტო (დღეებით)'), ('limited', 'რაოდენობრივი (ვიზიტებით)'), ('fixed', 'დროითი (თარიღიდან-თარიღამდე)')], max_length=20, verbose_name='ტიპი'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.CharField(max_length=100, verbose_name='დასახელება'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ფასი'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='visit_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ვიზიტების რაოდენობა'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='თანხა'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='gymapp.client', verbose_name='კლიენტი'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='გადახდის დრო'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='gymapp.membership', verbose_name='აბონემენტი'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'ქეში'), ('card', 'ბარათი'), ('transfer', 'ტრანსფერი')], max_length=20, verbose_name='გადახდის მეთოდი'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='სახელი'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='გვარი'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='ტელეფონი'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, verbose_name='სპეციალიზაცია'),
        ),
    ]
