# Generated by Django 5.2.11 on 2026-02-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_client_created_at_payment_fixed_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='active_membership',
        ),
        migrations.RemoveField(
            model_name='client',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='membership',
        ),
        migrations.DeleteModel(
            name='CheckIn',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
