# Generated by Django 5.2.11 on 2026-02-16 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gymapp', '0003_remove_client_active_membership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='სახელი')),
                ('last_name', models.CharField(max_length=100, verbose_name='გვარი')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='დაბადების თარიღი')),
                ('gender', models.CharField(blank=True, choices=[('male', 'მამრობითი'), ('female', 'მდედრობითი'), ('other', 'სხვა')], max_length=10, null=True, verbose_name='სქესი')),
                ('phone', models.CharField(max_length=20, verbose_name='ტელეფონი')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ელ. ფოსტა')),
                ('organization', models.CharField(blank=True, max_length=150, verbose_name='ორგანიზაცია')),
                ('card_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='ბარათის ნომერი')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients/photos/', verbose_name='ფოტოსურათი')),
                ('membership_start', models.DateField(blank=True, null=True, verbose_name='დაწყების თარიღი')),
                ('membership_end', models.DateField(blank=True, null=True, verbose_name='დასრულების თარიღი')),
                ('remaining_visits', models.PositiveIntegerField(blank=True, null=True, verbose_name='დარჩენილი ვიზიტები')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის დრო')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='დასახელება')),
                ('membership_type', models.CharField(choices=[('unlimited', 'ულიმიტო (დღეებით)'), ('limited', 'რაოდენობრივი (ვიზიტებით)'), ('fixed', 'დროითი (თარიღიდან-თარიღამდე)')], max_length=20, verbose_name='ტიპი')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ფასი')),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='ვადა (დღეებში)')),
                ('visit_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='ვიზიტების რაოდენობა')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='სახელი')),
                ('last_name', models.CharField(max_length=100, verbose_name='გვარი')),
                ('phone', models.CharField(max_length=20, verbose_name='ტელეფონი')),
                ('specialization', models.CharField(blank=True, max_length=255, verbose_name='სპეციალიზაცია')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შესვლის დრო')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='gymapp.client', verbose_name='კლიენტი')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='active_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_clients', to='gymapp.membership', verbose_name='აქტიური აბონემენტი'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_start', models.DateField(blank=True, null=True, verbose_name='Fixed Start (თუ fixed)')),
                ('fixed_end', models.DateField(blank=True, null=True, verbose_name='Fixed End (თუ fixed)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='თანხა')),
                ('method', models.CharField(choices=[('cash', 'ქეში'), ('card', 'ბარათი'), ('transfer', 'ტრანსფერი')], max_length=20, verbose_name='გადახდის მეთოდი')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='გადახდის დრო')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='gymapp.client', verbose_name='კლიენტი')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='gymapp.membership', verbose_name='აბონემენტი')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='gymapp.trainer', verbose_name='ტრენერი'),
        ),
    ]
