# Generated by Django 5.2.11 on 2026-02-16 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='active_membership',
        ),
        migrations.RemoveField(
            model_name='client',
            name='membership_end',
        ),
        migrations.RemoveField(
            model_name='client',
            name='membership_start',
        ),
        migrations.RemoveField(
            model_name='client',
            name='remaining_visits',
        ),
        migrations.CreateModel(
            name='ClientMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='დაწყების თარიღი')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='დასრულების თარიღი')),
                ('remaining_visits', models.PositiveIntegerField(blank=True, null=True, verbose_name='დარჩენილი ვიზიტები')),
                ('status', models.CharField(choices=[('active', 'აქტიური'), ('expired', 'ვადაგასული'), ('paused', 'დაპაუზებული')], default='active', max_length=10, verbose_name='სტატუსი')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gymapp.client', verbose_name='კლიენტი')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_memberships', to='gymapp.membership', verbose_name='აბონემენტი')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='gymapp_clie_client__e792e2_idx'), models.Index(fields=['end_date'], name='gymapp_clie_end_dat_d52178_idx')],
            },
        ),
    ]
