# Generated by Django 5.2.11 on 2026-02-16 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0005_remove_client_active_membership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='trainer',
        ),
        migrations.AddField(
            model_name='payment',
            name='membership_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='აბონემენტის თანხა'),
        ),
        migrations.AddField(
            model_name='payment',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='gymapp.trainer', verbose_name='ტრენერი'),
        ),
        migrations.AddField(
            model_name='payment',
            name='trainer_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ტრენერის თანხა'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='სტავკა (₾)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='სულ თანხა'),
        ),
    ]
