# Generated by Django 5.2.11 on 2026-02-20 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0006_remove_client_trainer_payment_membership_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='operation_date',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='ოპერაციის თარიღი'),
        ),
    ]
