# Generated by Django 5.2.11 on 2026-02-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0007_payment_operation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='კომენტარი'),
        ),
    ]
