# Generated by Django 5.2.11 on 2026-03-04 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0008_client_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymapp.clientmembership'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='gymapp.client', verbose_name='კლიენტი'),
        ),
        migrations.AlterField(
            model_name='clientmembership',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='gymapp.client', verbose_name='კლიენტი'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='gymapp.membership', verbose_name='აბონემენტი'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'ქეში'), ('card', 'ბარათი'), ('transfer', 'გადმორიცხვა')], max_length=20, verbose_name='გადახდის მეთოდი'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='gymapp.trainer', verbose_name='ტრენერი'),
        ),
    ]
