# Generated by Django 5.2.11 on 2026-03-12 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0009_payment_client_membership_alter_checkin_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'დამატება'), ('delete', 'წაშლა')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'დასასინქრონიზებელია'), ('done', 'დასინქრონდა'), ('error', 'შეცდომა')], default='pending', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_tasks', to='gymapp.client')),
            ],
        ),
    ]
