# Generated by Django 5.2.11 on 2026-03-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0010_clientsync'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clientmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('client',), name='one_active_membership_per_client'),
        ),
    ]
