# Generated by Django 5.2.11 on 2026-03-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0011_clientmembership_one_active_membership_per_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Clients Pictures/', verbose_name='ფოტოსურათი'),
        ),
    ]
