# Generated by Django 5.2.11 on 2026-03-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0012_alter_client_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='passId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
