# Generated by Django 5.2.11 on 2026-04-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0014_cardpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpayment',
            name='method',
            field=models.CharField(blank=True, choices=[('cash', 'ქეში'), ('card', 'ბარათი'), ('transfer', 'გადმორიცხვა')], max_length=20, null=True, verbose_name='გადახდის მეთოდი'),
        ),
    ]
