# Generated by Django 5.2.11 on 2026-05-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0015_cardpayment_method'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clientmembership',
            name='one_active_membership_per_client',
        ),
    ]
