# Generated by Django 5.2.11 on 2026-07-31 18:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0016_remove_clientmembership_one_active_membership_per_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=20, max_digits=8, verbose_name='თანხა')),
                ('method', models.CharField(choices=[('cash', 'ქეში'), ('card', 'ბარათი'), ('transfer', 'გადმორიცხვა')], default='cash', max_length=20, verbose_name='გადახდის მეთოდი')),
                ('operation_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='ოპერაციის თარიღი')),
                ('comment', models.TextField(blank=True, default='', verbose_name='კომენტარი')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის დრო')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='one_time_payments', to='gymapp.client', verbose_name='კლიენტი')),
            ],
            options={
                'verbose_name': 'ერთჯერადი გადახდა',
                'verbose_name_plural': 'ერთჯერადი გადახდები',
                'ordering': ['-operation_date', '-id'],
                'indexes': [models.Index(fields=['operation_date'], name='gymapp_onet_operati_5e572f_idx'), models.Index(fields=['client', 'operation_date'], name='gymapp_onet_client__a7ebaa_idx')],
            },
        ),
    ]
